services:
  - type: web  # Важно: именно "web", а не "worker"
    name: polair-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # Убедитесь, что файл называется main.py
    envVars:
      - key: TOKEN
        value: "7382727613:AAG7_S2GFaNIv6czqj6vJrS1EGVsSFS0WkM"
      - key: ADMIN_ID
        value: "@f1sherFM"
    plan: free